addAssignees: false

addReviewers: true

useReviewGroups: true

reviewGroups:
  active:
    - MarcelMue
    - thcdrt
  general:
    - holyhope
    - sguyennet
    - jMonsinjon
    - steven-zou
    - mhurtrel
    - heww
    - bitsf
    - wangcanfengxs
    - Ghostbaby
    - soulseen
    - chlins
    - XavierDuthil
    - cndoit18
    - lubronzhan
    - yxxhero
    - wy65701436

skipKeywords:
  - WIP
  - wip
  - DO NOT MERGE

numberOfReviewers: 2
